# Grafana datasource provisioning for OpenGSLB Demo 5
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://10.50.0.30:9090
    isDefault: true
    editable: false
